name: CI Copier
on: [push]

# Automatically stop old builds on the same branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unittests:
    name: Check project generation
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # ensure that `sed` behaves well on both Linux and macOS
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # copier doesn't like shallow clones
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
      - name: Test
        run: pixi run test
